 development:
  :address: s3-amsterdam.accountservergroup.com
  :port: 587
  :domain: spizzicaluna.com
  :user_name: ordini@spizzicaluna.com
  :password: .#N>su1h@N:]]@q~|
  :authentication: plain
  :enable_starttls_auto: true
  :openssl_verify_mode: true

# development:
  # :address: s3-amsterdam.accountservergroup.com
  # :port: 465
  # :authentication: plain
  # :user_name: ordini@spizzicaluna.com
  # :password: .#N>su1h@N:]]@q~|
  # :enable_starttls_auto: true
# production:
  # :address: mail.spizzicaluna.com
  # :port: 2525
  # :authentication: plain
  # :user_name: ordini@spizzicaluna.com
  # :password: .#N>su1h@N:]]@q~|
  # :enable_starttls_auto: true

# development:
  # :address: smtp.gmail.com
  # :port: 587
  # :authentication: plain
  # :user_name: veontomo@gmail.com
  # :password: gH2U_ln.
  # :enable_starttls_auto: true
# production:
  # :address: smtp.gmail.com
  # :port: 587
  # :authentication: plain
  # :user_name: xxx
  # :password: yyy
  # :enable_starttls_auto: true