require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AromasController do

  # This should return the minimal set of attributes required to create a valid
  # Aroma. As you add validations to Aroma, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AromasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all aromas as @aromas" do
      aroma = Aroma.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aromas).should eq([aroma])
    end
  end

  describe "GET show" do
    it "assigns the requested aroma as @aroma" do
      aroma = Aroma.create! valid_attributes
      get :show, {:id => aroma.to_param}, valid_session
      assigns(:aroma).should eq(aroma)
    end
  end

  describe "GET new" do
    it "assigns a new aroma as @aroma" do
      get :new, {}, valid_session
      assigns(:aroma).should be_a_new(Aroma)
    end
  end

  describe "GET edit" do
    it "assigns the requested aroma as @aroma" do
      aroma = Aroma.create! valid_attributes
      get :edit, {:id => aroma.to_param}, valid_session
      assigns(:aroma).should eq(aroma)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Aroma" do
        expect {
          post :create, {:aroma => valid_attributes}, valid_session
        }.to change(Aroma, :count).by(1)
      end

      it "assigns a newly created aroma as @aroma" do
        post :create, {:aroma => valid_attributes}, valid_session
        assigns(:aroma).should be_a(Aroma)
        assigns(:aroma).should be_persisted
      end

      it "redirects to the created aroma" do
        post :create, {:aroma => valid_attributes}, valid_session
        response.should redirect_to(Aroma.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved aroma as @aroma" do
        # Trigger the behavior that occurs when invalid params are submitted
        Aroma.any_instance.stub(:save).and_return(false)
        post :create, {:aroma => { "name" => "invalid value" }}, valid_session
        assigns(:aroma).should be_a_new(Aroma)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Aroma.any_instance.stub(:save).and_return(false)
        post :create, {:aroma => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested aroma" do
        aroma = Aroma.create! valid_attributes
        # Assuming there are no other aromas in the database, this
        # specifies that the Aroma created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Aroma.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => aroma.to_param, :aroma => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested aroma as @aroma" do
        aroma = Aroma.create! valid_attributes
        put :update, {:id => aroma.to_param, :aroma => valid_attributes}, valid_session
        assigns(:aroma).should eq(aroma)
      end

      it "redirects to the aroma" do
        aroma = Aroma.create! valid_attributes
        put :update, {:id => aroma.to_param, :aroma => valid_attributes}, valid_session
        response.should redirect_to(aroma)
      end
    end

    describe "with invalid params" do
      it "assigns the aroma as @aroma" do
        aroma = Aroma.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Aroma.any_instance.stub(:save).and_return(false)
        put :update, {:id => aroma.to_param, :aroma => { "name" => "invalid value" }}, valid_session
        assigns(:aroma).should eq(aroma)
      end

      it "re-renders the 'edit' template" do
        aroma = Aroma.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Aroma.any_instance.stub(:save).and_return(false)
        put :update, {:id => aroma.to_param, :aroma => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested aroma" do
      aroma = Aroma.create! valid_attributes
      expect {
        delete :destroy, {:id => aroma.to_param}, valid_session
      }.to change(Aroma, :count).by(-1)
    end

    it "redirects to the aromas list" do
      aroma = Aroma.create! valid_attributes
      delete :destroy, {:id => aroma.to_param}, valid_session
      response.should redirect_to(aromas_url)
    end
  end

end
