require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BeerStylesController do

  # This should return the minimal set of attributes required to create a valid
  # BeerStyle. As you add validations to BeerStyle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BeerStylesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all beer_styles as @beer_styles" do
      beer_style = BeerStyle.create! valid_attributes
      get :index, {}, valid_session
      assigns(:beer_styles).should eq([beer_style])
    end
  end

  describe "GET show" do
    it "assigns the requested beer_style as @beer_style" do
      beer_style = BeerStyle.create! valid_attributes
      get :show, {:id => beer_style.to_param}, valid_session
      assigns(:beer_style).should eq(beer_style)
    end
  end

  describe "GET new" do
    it "assigns a new beer_style as @beer_style" do
      get :new, {}, valid_session
      assigns(:beer_style).should be_a_new(BeerStyle)
    end
  end

  describe "GET edit" do
    it "assigns the requested beer_style as @beer_style" do
      beer_style = BeerStyle.create! valid_attributes
      get :edit, {:id => beer_style.to_param}, valid_session
      assigns(:beer_style).should eq(beer_style)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BeerStyle" do
        expect {
          post :create, {:beer_style => valid_attributes}, valid_session
        }.to change(BeerStyle, :count).by(1)
      end

      it "assigns a newly created beer_style as @beer_style" do
        post :create, {:beer_style => valid_attributes}, valid_session
        assigns(:beer_style).should be_a(BeerStyle)
        assigns(:beer_style).should be_persisted
      end

      it "redirects to the created beer_style" do
        post :create, {:beer_style => valid_attributes}, valid_session
        response.should redirect_to(BeerStyle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved beer_style as @beer_style" do
        # Trigger the behavior that occurs when invalid params are submitted
        BeerStyle.any_instance.stub(:save).and_return(false)
        post :create, {:beer_style => { "name" => "invalid value" }}, valid_session
        assigns(:beer_style).should be_a_new(BeerStyle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BeerStyle.any_instance.stub(:save).and_return(false)
        post :create, {:beer_style => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested beer_style" do
        beer_style = BeerStyle.create! valid_attributes
        # Assuming there are no other beer_styles in the database, this
        # specifies that the BeerStyle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BeerStyle.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => beer_style.to_param, :beer_style => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested beer_style as @beer_style" do
        beer_style = BeerStyle.create! valid_attributes
        put :update, {:id => beer_style.to_param, :beer_style => valid_attributes}, valid_session
        assigns(:beer_style).should eq(beer_style)
      end

      it "redirects to the beer_style" do
        beer_style = BeerStyle.create! valid_attributes
        put :update, {:id => beer_style.to_param, :beer_style => valid_attributes}, valid_session
        response.should redirect_to(beer_style)
      end
    end

    describe "with invalid params" do
      it "assigns the beer_style as @beer_style" do
        beer_style = BeerStyle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BeerStyle.any_instance.stub(:save).and_return(false)
        put :update, {:id => beer_style.to_param, :beer_style => { "name" => "invalid value" }}, valid_session
        assigns(:beer_style).should eq(beer_style)
      end

      it "re-renders the 'edit' template" do
        beer_style = BeerStyle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BeerStyle.any_instance.stub(:save).and_return(false)
        put :update, {:id => beer_style.to_param, :beer_style => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested beer_style" do
      beer_style = BeerStyle.create! valid_attributes
      expect {
        delete :destroy, {:id => beer_style.to_param}, valid_session
      }.to change(BeerStyle, :count).by(-1)
    end

    it "redirects to the beer_styles list" do
      beer_style = BeerStyle.create! valid_attributes
      delete :destroy, {:id => beer_style.to_param}, valid_session
      response.should redirect_to(beer_styles_url)
    end
  end

end
