require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BruschettaController do

  # This should return the minimal set of attributes required to create a valid
  # Bruschettum. As you add validations to Bruschettum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BruschettaController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bruschetta as @bruschetta" do
      bruschettum = Bruschettum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bruschetta).should eq([bruschettum])
    end
  end

  describe "GET show" do
    it "assigns the requested bruschettum as @bruschettum" do
      bruschettum = Bruschettum.create! valid_attributes
      get :show, {:id => bruschettum.to_param}, valid_session
      assigns(:bruschettum).should eq(bruschettum)
    end
  end

  describe "GET new" do
    it "assigns a new bruschettum as @bruschettum" do
      get :new, {}, valid_session
      assigns(:bruschettum).should be_a_new(Bruschettum)
    end
  end

  describe "GET edit" do
    it "assigns the requested bruschettum as @bruschettum" do
      bruschettum = Bruschettum.create! valid_attributes
      get :edit, {:id => bruschettum.to_param}, valid_session
      assigns(:bruschettum).should eq(bruschettum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bruschettum" do
        expect {
          post :create, {:bruschettum => valid_attributes}, valid_session
        }.to change(Bruschettum, :count).by(1)
      end

      it "assigns a newly created bruschettum as @bruschettum" do
        post :create, {:bruschettum => valid_attributes}, valid_session
        assigns(:bruschettum).should be_a(Bruschettum)
        assigns(:bruschettum).should be_persisted
      end

      it "redirects to the created bruschettum" do
        post :create, {:bruschettum => valid_attributes}, valid_session
        response.should redirect_to(Bruschettum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bruschettum as @bruschettum" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bruschettum.any_instance.stub(:save).and_return(false)
        post :create, {:bruschettum => { "name" => "invalid value" }}, valid_session
        assigns(:bruschettum).should be_a_new(Bruschettum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bruschettum.any_instance.stub(:save).and_return(false)
        post :create, {:bruschettum => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bruschettum" do
        bruschettum = Bruschettum.create! valid_attributes
        # Assuming there are no other bruschetta in the database, this
        # specifies that the Bruschettum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bruschettum.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => bruschettum.to_param, :bruschettum => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested bruschettum as @bruschettum" do
        bruschettum = Bruschettum.create! valid_attributes
        put :update, {:id => bruschettum.to_param, :bruschettum => valid_attributes}, valid_session
        assigns(:bruschettum).should eq(bruschettum)
      end

      it "redirects to the bruschettum" do
        bruschettum = Bruschettum.create! valid_attributes
        put :update, {:id => bruschettum.to_param, :bruschettum => valid_attributes}, valid_session
        response.should redirect_to(bruschettum)
      end
    end

    describe "with invalid params" do
      it "assigns the bruschettum as @bruschettum" do
        bruschettum = Bruschettum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bruschettum.any_instance.stub(:save).and_return(false)
        put :update, {:id => bruschettum.to_param, :bruschettum => { "name" => "invalid value" }}, valid_session
        assigns(:bruschettum).should eq(bruschettum)
      end

      it "re-renders the 'edit' template" do
        bruschettum = Bruschettum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bruschettum.any_instance.stub(:save).and_return(false)
        put :update, {:id => bruschettum.to_param, :bruschettum => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bruschettum" do
      bruschettum = Bruschettum.create! valid_attributes
      expect {
        delete :destroy, {:id => bruschettum.to_param}, valid_session
      }.to change(Bruschettum, :count).by(-1)
    end

    it "redirects to the bruschetta list" do
      bruschettum = Bruschettum.create! valid_attributes
      delete :destroy, {:id => bruschettum.to_param}, valid_session
      response.should redirect_to(bruschetta_url)
    end
  end

end
