require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FoodcategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Foodcategory. As you add validations to Foodcategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FoodcategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all foodcategories as @foodcategories" do
      foodcategory = Foodcategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:foodcategories).should eq([foodcategory])
    end
  end

  describe "GET show" do
    it "assigns the requested foodcategory as @foodcategory" do
      foodcategory = Foodcategory.create! valid_attributes
      get :show, {:id => foodcategory.to_param}, valid_session
      assigns(:foodcategory).should eq(foodcategory)
    end
  end

  describe "GET new" do
    it "assigns a new foodcategory as @foodcategory" do
      get :new, {}, valid_session
      assigns(:foodcategory).should be_a_new(Foodcategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested foodcategory as @foodcategory" do
      foodcategory = Foodcategory.create! valid_attributes
      get :edit, {:id => foodcategory.to_param}, valid_session
      assigns(:foodcategory).should eq(foodcategory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Foodcategory" do
        expect {
          post :create, {:foodcategory => valid_attributes}, valid_session
        }.to change(Foodcategory, :count).by(1)
      end

      it "assigns a newly created foodcategory as @foodcategory" do
        post :create, {:foodcategory => valid_attributes}, valid_session
        assigns(:foodcategory).should be_a(Foodcategory)
        assigns(:foodcategory).should be_persisted
      end

      it "redirects to the created foodcategory" do
        post :create, {:foodcategory => valid_attributes}, valid_session
        response.should redirect_to(Foodcategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved foodcategory as @foodcategory" do
        # Trigger the behavior that occurs when invalid params are submitted
        Foodcategory.any_instance.stub(:save).and_return(false)
        post :create, {:foodcategory => { "name" => "invalid value" }}, valid_session
        assigns(:foodcategory).should be_a_new(Foodcategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Foodcategory.any_instance.stub(:save).and_return(false)
        post :create, {:foodcategory => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested foodcategory" do
        foodcategory = Foodcategory.create! valid_attributes
        # Assuming there are no other foodcategories in the database, this
        # specifies that the Foodcategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Foodcategory.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => foodcategory.to_param, :foodcategory => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested foodcategory as @foodcategory" do
        foodcategory = Foodcategory.create! valid_attributes
        put :update, {:id => foodcategory.to_param, :foodcategory => valid_attributes}, valid_session
        assigns(:foodcategory).should eq(foodcategory)
      end

      it "redirects to the foodcategory" do
        foodcategory = Foodcategory.create! valid_attributes
        put :update, {:id => foodcategory.to_param, :foodcategory => valid_attributes}, valid_session
        response.should redirect_to(foodcategory)
      end
    end

    describe "with invalid params" do
      it "assigns the foodcategory as @foodcategory" do
        foodcategory = Foodcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Foodcategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => foodcategory.to_param, :foodcategory => { "name" => "invalid value" }}, valid_session
        assigns(:foodcategory).should eq(foodcategory)
      end

      it "re-renders the 'edit' template" do
        foodcategory = Foodcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Foodcategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => foodcategory.to_param, :foodcategory => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested foodcategory" do
      foodcategory = Foodcategory.create! valid_attributes
      expect {
        delete :destroy, {:id => foodcategory.to_param}, valid_session
      }.to change(Foodcategory, :count).by(-1)
    end

    it "redirects to the foodcategories list" do
      foodcategory = Foodcategory.create! valid_attributes
      delete :destroy, {:id => foodcategory.to_param}, valid_session
      response.should redirect_to(foodcategories_url)
    end
  end

end
