require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItemstatusesController do

  # This should return the minimal set of attributes required to create a valid
  # Itemstatus. As you add validations to Itemstatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItemstatusesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all itemstatuses as @itemstatuses" do
      itemstatus = Itemstatus.create! valid_attributes
      get :index, {}, valid_session
      assigns(:itemstatuses).should eq([itemstatus])
    end
  end

  describe "GET show" do
    it "assigns the requested itemstatus as @itemstatus" do
      itemstatus = Itemstatus.create! valid_attributes
      get :show, {:id => itemstatus.to_param}, valid_session
      assigns(:itemstatus).should eq(itemstatus)
    end
  end

  describe "GET new" do
    it "assigns a new itemstatus as @itemstatus" do
      get :new, {}, valid_session
      assigns(:itemstatus).should be_a_new(Itemstatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested itemstatus as @itemstatus" do
      itemstatus = Itemstatus.create! valid_attributes
      get :edit, {:id => itemstatus.to_param}, valid_session
      assigns(:itemstatus).should eq(itemstatus)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Itemstatus" do
        expect {
          post :create, {:itemstatus => valid_attributes}, valid_session
        }.to change(Itemstatus, :count).by(1)
      end

      it "assigns a newly created itemstatus as @itemstatus" do
        post :create, {:itemstatus => valid_attributes}, valid_session
        assigns(:itemstatus).should be_a(Itemstatus)
        assigns(:itemstatus).should be_persisted
      end

      it "redirects to the created itemstatus" do
        post :create, {:itemstatus => valid_attributes}, valid_session
        response.should redirect_to(Itemstatus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved itemstatus as @itemstatus" do
        # Trigger the behavior that occurs when invalid params are submitted
        Itemstatus.any_instance.stub(:save).and_return(false)
        post :create, {:itemstatus => { "name" => "invalid value" }}, valid_session
        assigns(:itemstatus).should be_a_new(Itemstatus)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Itemstatus.any_instance.stub(:save).and_return(false)
        post :create, {:itemstatus => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested itemstatus" do
        itemstatus = Itemstatus.create! valid_attributes
        # Assuming there are no other itemstatuses in the database, this
        # specifies that the Itemstatus created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Itemstatus.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => itemstatus.to_param, :itemstatus => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested itemstatus as @itemstatus" do
        itemstatus = Itemstatus.create! valid_attributes
        put :update, {:id => itemstatus.to_param, :itemstatus => valid_attributes}, valid_session
        assigns(:itemstatus).should eq(itemstatus)
      end

      it "redirects to the itemstatus" do
        itemstatus = Itemstatus.create! valid_attributes
        put :update, {:id => itemstatus.to_param, :itemstatus => valid_attributes}, valid_session
        response.should redirect_to(itemstatus)
      end
    end

    describe "with invalid params" do
      it "assigns the itemstatus as @itemstatus" do
        itemstatus = Itemstatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Itemstatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => itemstatus.to_param, :itemstatus => { "name" => "invalid value" }}, valid_session
        assigns(:itemstatus).should eq(itemstatus)
      end

      it "re-renders the 'edit' template" do
        itemstatus = Itemstatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Itemstatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => itemstatus.to_param, :itemstatus => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested itemstatus" do
      itemstatus = Itemstatus.create! valid_attributes
      expect {
        delete :destroy, {:id => itemstatus.to_param}, valid_session
      }.to change(Itemstatus, :count).by(-1)
    end

    it "redirects to the itemstatuses list" do
      itemstatus = Itemstatus.create! valid_attributes
      delete :destroy, {:id => itemstatus.to_param}, valid_session
      response.should redirect_to(itemstatuses_url)
    end
  end

end
