require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OnePhotosController do

  # This should return the minimal set of attributes required to create a valid
  # OnePhoto. As you add validations to OnePhoto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OnePhotosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all one_photos as @one_photos" do
      one_photo = OnePhoto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:one_photos).should eq([one_photo])
    end
  end

  describe "GET show" do
    it "assigns the requested one_photo as @one_photo" do
      one_photo = OnePhoto.create! valid_attributes
      get :show, {:id => one_photo.to_param}, valid_session
      assigns(:one_photo).should eq(one_photo)
    end
  end

  describe "GET new" do
    it "assigns a new one_photo as @one_photo" do
      get :new, {}, valid_session
      assigns(:one_photo).should be_a_new(OnePhoto)
    end
  end

  describe "GET edit" do
    it "assigns the requested one_photo as @one_photo" do
      one_photo = OnePhoto.create! valid_attributes
      get :edit, {:id => one_photo.to_param}, valid_session
      assigns(:one_photo).should eq(one_photo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OnePhoto" do
        expect {
          post :create, {:one_photo => valid_attributes}, valid_session
        }.to change(OnePhoto, :count).by(1)
      end

      it "assigns a newly created one_photo as @one_photo" do
        post :create, {:one_photo => valid_attributes}, valid_session
        assigns(:one_photo).should be_a(OnePhoto)
        assigns(:one_photo).should be_persisted
      end

      it "redirects to the created one_photo" do
        post :create, {:one_photo => valid_attributes}, valid_session
        response.should redirect_to(OnePhoto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved one_photo as @one_photo" do
        # Trigger the behavior that occurs when invalid params are submitted
        OnePhoto.any_instance.stub(:save).and_return(false)
        post :create, {:one_photo => {  }}, valid_session
        assigns(:one_photo).should be_a_new(OnePhoto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OnePhoto.any_instance.stub(:save).and_return(false)
        post :create, {:one_photo => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested one_photo" do
        one_photo = OnePhoto.create! valid_attributes
        # Assuming there are no other one_photos in the database, this
        # specifies that the OnePhoto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OnePhoto.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => one_photo.to_param, :one_photo => { "these" => "params" }}, valid_session
      end

      it "assigns the requested one_photo as @one_photo" do
        one_photo = OnePhoto.create! valid_attributes
        put :update, {:id => one_photo.to_param, :one_photo => valid_attributes}, valid_session
        assigns(:one_photo).should eq(one_photo)
      end

      it "redirects to the one_photo" do
        one_photo = OnePhoto.create! valid_attributes
        put :update, {:id => one_photo.to_param, :one_photo => valid_attributes}, valid_session
        response.should redirect_to(one_photo)
      end
    end

    describe "with invalid params" do
      it "assigns the one_photo as @one_photo" do
        one_photo = OnePhoto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OnePhoto.any_instance.stub(:save).and_return(false)
        put :update, {:id => one_photo.to_param, :one_photo => {  }}, valid_session
        assigns(:one_photo).should eq(one_photo)
      end

      it "re-renders the 'edit' template" do
        one_photo = OnePhoto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OnePhoto.any_instance.stub(:save).and_return(false)
        put :update, {:id => one_photo.to_param, :one_photo => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested one_photo" do
      one_photo = OnePhoto.create! valid_attributes
      expect {
        delete :destroy, {:id => one_photo.to_param}, valid_session
      }.to change(OnePhoto, :count).by(-1)
    end

    it "redirects to the one_photos list" do
      one_photo = OnePhoto.create! valid_attributes
      delete :destroy, {:id => one_photo.to_param}, valid_session
      response.should redirect_to(one_photos_url)
    end
  end

end
