require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrenotationsController do

  # This should return the minimal set of attributes required to create a valid
  # Prenotation. As you add validations to Prenotation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrenotationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all prenotations as @prenotations" do
      prenotation = Prenotation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prenotations).should eq([prenotation])
    end
  end

  describe "GET show" do
    it "assigns the requested prenotation as @prenotation" do
      prenotation = Prenotation.create! valid_attributes
      get :show, {:id => prenotation.to_param}, valid_session
      assigns(:prenotation).should eq(prenotation)
    end
  end

  describe "GET new" do
    it "assigns a new prenotation as @prenotation" do
      get :new, {}, valid_session
      assigns(:prenotation).should be_a_new(Prenotation)
    end
  end

  describe "GET edit" do
    it "assigns the requested prenotation as @prenotation" do
      prenotation = Prenotation.create! valid_attributes
      get :edit, {:id => prenotation.to_param}, valid_session
      assigns(:prenotation).should eq(prenotation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Prenotation" do
        expect {
          post :create, {:prenotation => valid_attributes}, valid_session
        }.to change(Prenotation, :count).by(1)
      end

      it "assigns a newly created prenotation as @prenotation" do
        post :create, {:prenotation => valid_attributes}, valid_session
        assigns(:prenotation).should be_a(Prenotation)
        assigns(:prenotation).should be_persisted
      end

      it "redirects to the created prenotation" do
        post :create, {:prenotation => valid_attributes}, valid_session
        response.should redirect_to(Prenotation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prenotation as @prenotation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prenotation.any_instance.stub(:save).and_return(false)
        post :create, {:prenotation => { "name" => "invalid value" }}, valid_session
        assigns(:prenotation).should be_a_new(Prenotation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prenotation.any_instance.stub(:save).and_return(false)
        post :create, {:prenotation => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prenotation" do
        prenotation = Prenotation.create! valid_attributes
        # Assuming there are no other prenotations in the database, this
        # specifies that the Prenotation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Prenotation.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => prenotation.to_param, :prenotation => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested prenotation as @prenotation" do
        prenotation = Prenotation.create! valid_attributes
        put :update, {:id => prenotation.to_param, :prenotation => valid_attributes}, valid_session
        assigns(:prenotation).should eq(prenotation)
      end

      it "redirects to the prenotation" do
        prenotation = Prenotation.create! valid_attributes
        put :update, {:id => prenotation.to_param, :prenotation => valid_attributes}, valid_session
        response.should redirect_to(prenotation)
      end
    end

    describe "with invalid params" do
      it "assigns the prenotation as @prenotation" do
        prenotation = Prenotation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prenotation.any_instance.stub(:save).and_return(false)
        put :update, {:id => prenotation.to_param, :prenotation => { "name" => "invalid value" }}, valid_session
        assigns(:prenotation).should eq(prenotation)
      end

      it "re-renders the 'edit' template" do
        prenotation = Prenotation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prenotation.any_instance.stub(:save).and_return(false)
        put :update, {:id => prenotation.to_param, :prenotation => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prenotation" do
      prenotation = Prenotation.create! valid_attributes
      expect {
        delete :destroy, {:id => prenotation.to_param}, valid_session
      }.to change(Prenotation, :count).by(-1)
    end

    it "redirects to the prenotations list" do
      prenotation = Prenotation.create! valid_attributes
      delete :destroy, {:id => prenotation.to_param}, valid_session
      response.should redirect_to(prenotations_url)
    end
  end

end
